aws/aws-sdk-js-crypto-helpers

packages/crc32/README.md
packages/ie11-detection/README.md
packages/random-source-browser/README.md
packages/random-source-node/README.md
packages/random-source-universal/README.md
packages/sha256-browser/README.md
packages/sha256-js/README.md
packages/sha256-universal/README.md
packages/supports-web-crypto/README.md

resolves #3
The npm package scope in the readme should match the correct package scope.

doc: Update readme to reference the correct group

---

package.json

fix: Update Lerna version

---

.gitignore

Copy .gitignore from the ESDK JS

fix: Update gitignore

---

.github/workflows/ci-unit-tests.yaml
.github/workflows/promote-to-master-pr.yaml

chore: Adding CI using GitHub Actions

---

.github/workflows/ci-unit-tests.yaml

chore: fix YAML formating

---

README.md

chore: Add security issue notification to readme

---

package.json

Set license to Apache-2.0 in package.json

---

package-lock.json
package.json
packages/random-source-node/package.json
packages/random-source-universal/package.json
packages/sha256-browser/package.json
packages/sha256-js/package.json
packages/sha256-universal/package.json

Dependabot does not do a great job
of updating monorepos that use npm.

chore: update versions

---

.github/workflows/ci-unit-tests.yaml
.gitignore
codebuild/release/prod-release.yml
package-lock.json
package.json
util/local_verdaccio_publish
util/verify_release
verdaccio/config.yaml
verdaccio/integration/Readme.md
verdaccio/integration/package.json
verdaccio/npmrc

Added verdaccio publish testing.
Added CodeBuild spec to version and publish releases.

chore: add release automation

---

.github/dependabot.yml

_Issue #, if available:_ Enable Dependabot
_Description of changes:_ Copy Dependabot yaml from ESDK-JS to enable Dependabot

ci(dependabot): enable dependabot

---

package-lock.json
package.json

chore: update lerna and verdaccio

---

packages/util/README.md

`packages/util` has the wrong readme file, updating to reflect contents of the `util` package

fix(docs): update README for packages/util

---

package-lock.json

*Issue #, if available:* Address issue in in-direct dev dependency parse-url 
*Description of changes:* Execute `npm ci; npm audit fix;`

chore: update dev deps

---

package-lock.json
packages/sha256-browser/README.md
packages/sha256-js/README.md
packages/sha256-js/test/jsSha256.test.ts
packages/sha256-universal/README.md

Adding Usage for hmac, updated tests to say hmac for clarity

fix(docs): sha256 packages, clarify hmac support

---

SUPPORT_POLICY.rst

Updating version support policy:
* 1.x has been EOS since 2022-04-15
* 2.x is on Maintenance; EOS 2023-07-11
* 3.x is GA

chore: Update version support policy

---

SUPPORT_POLICY.rst
package-lock.json

_Issue #, if available:_ N/A
_Description of changes:_ 
- Fix the package-lock for CI
- update the SUPPORT_POLICY for the recent 4.x release.

docs: update SUPPORT_POLICY

---

package-lock.json

Bump yaml from 2.2.1 to 2.2.2 to fix https://github.com/advisories/GHSA-f9xv-q969-pqx4

chore(deps-dev): Bump yaml from 2.2.1 to 2.2.2

---

codebuild/release/prod-release.yml

chore: update image

---

package-lock.json
package.json
packages/crc32/package.json
packages/crc32c/package.json
packages/random-source-browser/package.json
packages/random-source-node/package.json
packages/random-source-universal/package.json
packages/sha1-browser/package.json
packages/sha256-browser/package.json
packages/sha256-js/package.json
packages/sha256-universal/package.json
packages/supports-web-crypto/package.json
packages/util/package.json

_Issue #, if available:_ fixes #779, though a release will be needed.
Closes #781 
For package in packages:
```
if tslib & sdk/types:
npm add @aws-sdk/types@~3.413.0 tslib@~2.6.2
if tlsib & !sdk/types:
npm add tslib@~2.6.2
```

fix: pin @aws-sdk/types & tslib to minor

---

packages/crc32/package.json
packages/crc32c/package.json
packages/random-source-browser/package.json
packages/random-source-node/package.json
packages/random-source-universal/package.json
packages/sha1-browser/package.json
packages/sha256-browser/package.json
packages/sha256-js/package.json
packages/sha256-universal/package.json
packages/supports-web-crypto/package.json
packages/util/package.json

chore: Ship ES6 files in npm release

---

.github/workflows/ci-unit-tests.yaml
.github/workflows/daily_ci.yaml
.github/workflows/pull.yaml
.github/workflows/push.yaml

chore(CI): Added github workflows for daily CI
