- packages/crc32/.npmignore
- packages/ie11-detection/.npmignore
- packages/random-source-browser/.npmignore
- packages/random-source-node/.npmignore
- packages/random-source-universal/.npmignore
- packages/sha256-browser/.npmignore
- packages/sha256-js/.npmignore
- packages/sha256-universal/.npmignore
- packages/supports-web-crypto/.npmignore
This PR removes /src/ from .npmignore in every package so that original TS source files will be published to the npm registry. This is especially important for VSCode users because the VSCode debugger relies on source files for setting breakpoints in the debugger, for debugger call stacks, for "step into" original source, and any other debugger use-cases. Even outside of debugging use-cases, it's helpful for developers consuming transpiled libraries to have original source so they can better understand what the library is doing. Finally, some tools (e.g. https://github.com/Volune/source-map-loader/tree/fixes) will show warnings when sourcemaps are present but source files are missing, and this PR will fix these warnings.
This PR is analogous to aws-amplify/amplify-js#2680 which made the …
> fix: remove /src/ from .npmignore (for sourcemaps)

- packages/sha256-js/src/jsSha256.ts
Resolves #6
The underlying digest is synchronous.
The original version in the aws-sdk v2 exposed this synchronous version.
Wrapping up and exposing this function maintains backwards compatibility.
> feat(sha256-js): expose synchronous digest

- packages/sha256-browser/tsconfig.json
- packages/sha256-js/tsconfig.json
Both sha256-js and sha256-browser use `es2015.iterable`
> fix: es2015.iterable required

- .gitignore
- package-lock.json
- packages/.gitignore
- packages/crc32/.gitignore
- packages/crc32/package-lock.json
- packages/ie11-detection/.gitignore
- packages/ie11-detection/package-lock.json
- packages/random-source-browser/.gitignore
- packages/random-source-browser/package-lock.json
- packages/random-source-node/.gitignore
- packages/random-source-node/package-lock.json
- packages/random-source-universal/.gitignore
- packages/random-source-universal/package-lock.json
- packages/sha256-browser/.gitignore
- packages/sha256-browser/package-lock.json
- packages/sha256-js/.gitignore
- packages/sha256-js/package-lock.json
- packages/sha256-universal/.gitignore
- packages/sha256-universal/package-lock.json
- packages/supports-web-crypto/.gitignore
- packages/supports-web-crypto/package-lock.json
resolves #13
Lerna version 3.18.2 will version package-lock.json files.
This means that if they are in .gitingnore the version command will fail.
Better visibility into versions should help debugging.
> fix: lerna version maintains package-lock

- package-lock.json
_Issue:_ 
"npm install" reported 2 vulnerabilities on handlebars 4.5.1 (and prior) disclosed Nov 14, 2019: https://www.npmjs.com/advisories/1316
_Description of changes:_ 
Ran "npm audit fix" which updated package-lock.json to use handlebars 4.5.2. "npm install; npm run bootstrap" completed the file.
> fix: upgrade handlebars to address https://www.npmjs.com/advisories/1316

- package-lock.json
- package.json
*Issue #, if available:*
#16 
*Description of changes:*
We were pulling in mem@1.1.0 for yargs@8.0.2, but that version of yargs wasn't actually needed (lerna uses a newer version of yargs). By removing that dependency, we are no longer pulling in a vulnerable version of mem that could lead to a Denial of Service.
> fix: remove mem dependency to avoid DoS vulnerability

- .github/workflows/ci-unit-tests.yaml
Each GA step needs a `run` or a `uses`.
I do not see any advantage to having one step for each npm command.
Also, it should be `npm ci` to use the package-lock.json
> chore: Fix CI Action for run

- package-lock.json
- packages/crc32/package.json
- packages/random-source-browser/package.json
- packages/random-source-node/package.json
- packages/random-source-universal/package.json
- packages/sha256-browser/package.json
- packages/sha256-js/package.json
- packages/sha256-universal/package.json
*Issue #, if available:*
Refs: https://github.com/aws/aws-sdk-js-crypto-helpers/issues/18
*Description of changes:*
* switch to alpha releases of @aws-sdk packages
* Will mark for review once alpha packages are released
> chore: switch to alpha releases of @aws-sdk packages

- .github/workflows/ci-unit-tests.yaml
- README.md
- lerna.json
- package-lock.json
- package.json
- packages/crc32/package-lock.json
- packages/crc32/package.json
- packages/ie11-detection/package-lock.json
- packages/ie11-detection/package.json
- packages/random-source-browser/package-lock.json
- packages/random-source-browser/package.json
- packages/random-source-node/package-lock.json
- packages/random-source-node/package.json
- packages/random-source-universal/package-lock.json
- packages/random-source-universal/package.json
- packages/sha256-browser/package-lock.json
- packages/sha256-browser/package.json
- packages/sha256-js/package-lock.json
- packages/sha256-js/package.json
- packages/sha256-universal/package-lock.json
- packages/sha256-universal/package.json
- packages/supports-web-crypto/package-lock.json
- packages/supports-web-crypto/package.json
`lerna link convert`
This links all the packages to the root
and removes the need for `lerna bootstrap`.
This should help with dependabot PRs
as well as making `npm audit` just work.
This is also relevant to: #23 
> chore: Prep for dependabot

- package-lock.json
- package.json
- packages/crc32/test/index.test.ts
- packages/random-source-browser/package.json
- packages/random-source-node/package.json
- packages/random-source-universal/package.json
- packages/sha256-browser/package.json
- packages/sha256-js/package.json
- packages/sha256-universal/package.json
https://github.com/aws/aws-sdk-js-v3/pull/1241
https://github.com/aws/aws-sdk-js-v3/pull/1240
* Bump @aws-sdk packages to gamma
* Replace package @aws-sdk/util-utf8-universal to @aws-sdk/util-utf8-browser in the unit tests
/cc @seebees 
> bump aws-sdk to gamma

- packages/ie11-detection/tsconfig.json
- packages/ie11-detection/tsconfig.test.json
- packages/random-source-browser/tsconfig.json
- packages/random-source-browser/tsconfig.test.json
- packages/random-source-node/tsconfig.json
- packages/random-source-node/tsconfig.test.json
- packages/supports-web-crypto/tsconfig.json
- packages/supports-web-crypto/tsconfig.test.json
This PR changes `sourceRoot` to `rootDir` in tsconfig.json for 4 of the packages in this repo. (All other packages already used `rootDir`.) 
This change is helpful because using `sourceRoot` creates sourcemaps that some tools cannot read correctly, leading to build warnings and/or debuggers like VSCode being unable to debug into original source files.
Related: https://github.com/aws/aws-sdk-js-v3/pull/1462 includes a similar change for the SDKV3 repo.
BTW, this is a follow-up to my other sourcemap-related PR #5 that was merged last year. Slowly but surely I'm trying to get all AWS libraries to be easily debuggable with sourcemaps! ;-)
> fix: replace `sourceRoot` -> `rootDir` in tsconfig

- package-lock.json
- package.json
- packages/random-source-browser/package.json
- packages/random-source-node/package.json
- packages/random-source-universal/package.json
- packages/sha256-browser/package.json
- packages/sha256-js/package.json
- packages/sha256-universal/package.json
Similar to https://github.com/aws/aws-sdk-js-crypto-helpers/pull/144
AWS JavaScript SDK v3 has now published a Release Candidate https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-rc.1
* chore(deps-dev): remove unused dep @aws-sdk/util-buffer-from
* chore(deps-dev): bump @aws-sdk deps to rc
> chore(deps-dev): bump @aws-sdk deps to rc

- package-lock.json
- packages/random-source-browser/package.json
- packages/random-source-node/package.json
- packages/random-source-universal/package.json
- packages/sha256-browser/package.json
- packages/sha256-js/package.json
- packages/sha256-universal/package.json
AWS SDK v3 is now GA. Bump v3 dependencies to the GA version
/cc @seebees 
> chore: bump aws-sdk to 3.0.0

- .github/workflows/ci-unit-tests.yaml
Fixes: https://github.com/aws/aws-sdk-js-crypto-helpers/issues/179
chore(ci): add Node.js 14.x LTS
> chore(ci): add Node.js 14.x LTS

- package-lock.json
- packages/random-source-node/package.json
- packages/random-source-universal/package.json
- packages/sha256-browser/package.json
- packages/sha256-js/package.json
- packages/sha256-universal/package.json
Attempts to fix https://github.com/aws/aws-sdk-js-v3/issues/1842
move `@aws-sdk/types` to devDependencies
> fix(deps-dev): move @aws-sdk/types to devDependencies

- package-lock.json
- package.json
- util/verify_release
Adds a utility script to verify that a released package can be at least installed and loaded, along with a top-level npm script to run this for each package.
> chore: Add release verification script

- packages/sha256-browser/src/ie11Sha256.ts
https://github.com/aws/aws-sdk-js-v3/issues/2292
_Description of changes:_ Promise should reject with a JS error instead of a string.
> fix(sha256-browser): throw errors not string

- packages/crc32c/package.json
When running `lerna publish` to publish a new scoped package, if
`publishConfig.access` is unset, then the package is published with
private visibility ("restricted") by default [1]. Since this package is
intended for public consumption, we should configure this property
accordingly.
[1] https://github.com/lerna/lerna/tree/main/commands/publish#publishconfigaccess
> chore(crc32c): set publishConfig.access to public

- lerna.json
Reference: https://github.com/lerna/lerna#fixedlocked-mode-default
1. Currently the SDK create a new tag for each new version each subpackage. This results in having too many tags to maintain.
2. Using independent versioning also adds some unnecessary complexity over the release system.
3. Most popular monorepos use fixed versioning, like Lerna, Babel
See: aws-sdk-js-v3 switched to fixed versioning with their release candidate in aws/aws-sdk-js-v3#1248
And aws/aws-encryption-sdk-javascript#523
> chore: Use lerna fixed versioning

- util/verify_release
> fix: Adding ie11-detection dependency to sha1-browser

- packages/sha1-browser/package.json
> fix: Adding ie11-detection dep to sha1-browser

- packages/util/src/convertToBuffer.ts
Referencing an undefined directly variable is causing an issue compiling.
Especially in Webpack.
> fix: better pollyfill check for Buffer

- packages/crc32/src/index.ts
- packages/crc32c/src/index.ts
- packages/util/src/index.ts
- packages/util/src/uint32ArrayFrom.ts
_Issue #, if available:_ IE 11 does not support Array.from
_Description of changes:_ Use a manual Array initialization to populate a `Uint32Array`.
_Not Fixed:_ There are still no browsers tests.
> fix(crc32c): ie11 does not support Array.from

- packages/util/src/uint32ArrayFrom.ts
- packages/util/test/uint32ArrayFrom.test.ts
_Issue #, if available:_ #269
_Description of changes:_ 
1. Increment index in Uint32Array, which was not happening in the while loop.
2. Detect if UInt32Array.From is missing, as compared to the generic Array.From
PR is not yet tested on IE 11
> fix(uint32ArrayFrom): increment index & polyfill for Uint32Array

- package-lock.json
- package.json
Updates verdaccio dependency to deal with dependabot notice.
- updated verdaccio from `^5.1.6` to `^5.8.0`
- ran the following commands:
- `npm audit fix`
- `npm install verdaccio`
- `npm dedupe`
- `npm update verdaccio`
- `npm run verdaccio-publish`
- `npm run verdaccio-verfiy-publish --ci`
The following [lines](https://github.com/aws/aws-sdk-js-crypto-helpers/pull/326/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R2148-R2156) show that the audit worked (make sure to click on load diff )
> chore(deps-dev): update verdaccio

- package-lock.json
- package.json
- packages/crc32/package.json
- packages/crc32c/package.json
- packages/random-source-node/package.json
- packages/random-source-universal/package.json
- packages/sha1-browser/package.json
- packages/sha256-browser/package.json
- packages/sha256-js/package.json
- packages/sha256-universal/package.json
- packages/util/package.json
_Issue #, if available:_ #337
_Description of changes:_ Updated @aws-sdk/types via the following pattern:
1. `npm install @aws-sdk/types@^3.110.0 --save-dev`
2. For package in packages:
`cd package; less package.json; if aws-sdk/types present: npm install @aws-sdk/types@^3.110.0`
3. Test those changes
4. Check package lock for any hold out types@^3.55.0, see `@aws-sdk/hash-node` bringing it in
5. `cd packages/sha256-universall; npm install @aws-sdk/hash-node@^3.110.0`
6. From root, run `npm run clean; npm run test;`
Should close #337 
> fix[#337]: update @aws-sdk/types

- packages/crc32/package.json
- packages/crc32c/package.json
- packages/ie11-detection/package.json
- packages/random-source-browser/package.json
- packages/random-source-node/package.json
- packages/random-source-universal/package.json
- packages/sha1-browser/package.json
- packages/sha256-browser/package.json
- packages/sha256-js/package.json
- packages/sha256-universal/package.json
- packages/supports-web-crypto/package.json
- packages/util/package.json
Fixes: https://github.com/aws/aws-sdk-js-crypto-helpers/issues/379
Adds homepage field in package.json
> chore: add homepage field in package.json

- .github/workflows/ci-unit-tests.yaml
- codebuild/release/publish.yml
- codebuild/release/version.yml
- package-lock.json
Remove CI testing under Node 12
> feat!: deprecate node12. BREAKING CHANGE: Remove node12 from CI

- packages/sha256-universal/package.json
Webpack 5 makes browser polyfills explicit. Webpack detects `@aws-sdk/hash-node` as something that includes node features to potentially pollfill while using `@aws-crypto/sha256-universal`. This can be resolved via a webpack config, but better to resolve the typo here.
```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "buffer": false }
```
I assume a similar issue is happening …
> fix: correct package naming in "browser" fields

- .github/workflows/ci-unit-tests.yaml
- .gitignore
- codebuild/release/publish.yml
- codebuild/release/version.yml
- package-lock.json
_Issue #, if available:_ Drop Node 14
Stop testing with Node 14.
Test Against Node 16, 18, & 20.
BREAKING CHANGE: Node 14 is no longer supported nor tested.
> chore!: Drop Node 14 Support

- package-lock.json
- package.json
- packages/crc32/test/index.test.ts
- packages/crc32c/test/index.test.ts
- packages/sha1-browser/package.json
- packages/sha1-browser/src/webCryptoSha1.ts
- packages/sha1-browser/test/webCryptoSha1.test.ts
- packages/sha256-browser/package.json
- packages/sha256-browser/test/webCryptoSha256.test.ts
- packages/util/package.json
- packages/util/src/convertToBuffer.ts
@aws-sdk/util-utf8-browser is depricated,
update to the new version
fixes: #699
> feat: Use @smithy/util-utf8

- packages/random-source-universal/README.md
Update the README example code to match the package it is for.
_Description of changes:_ Not sure if I'm missing something, I think this is a typo? The example code in the README for the `random-source-universal` package, uses the `random-source-node` package instead.
> docs[random-source-universal]: fix README.md

- package-lock.json
- package.json
- packages/sha256-js/src/knownHashes.fixture.ts
These packages:
- @aws-sdk/util-buffer-from
- @aws-sdk/util-hex-encoding
have been depricated in favor of:
- @smithy/util-buffer-from
- @smithy/util-hex-encoding
> chore: update depricated packages
